apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: klaus-mandola-poi-gateway-app-dev
  annotations:
    argocd/app-name: klaus-mandola-poi-gateway-app-dev
    backstage.io/kubernetes-id: klaus-mandola-poi-gateway-app
    backstage.io/kubernetes-namespace: klaus-mandola
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-demo/klaus-mandola-gateway
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/dev-pipelines/ns/klaus-mandola/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/k8s/ns/klaus-mandola/deployments/klaus-mandola-poi-gateway-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/#https://github.com/rhdh23-demo/klaus-mandola-gateway?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/meiersheinz"
  system: workshop-system-klaus-mandola
  providesApis:
    - gateway-api-klaus-mandola
  consumesApis:
    - backend-api-klaus-mandola
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-klaus-mandola
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/meiersheinz"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: gateway-api-klaus-mandola
  description: API surface exposed to interact with Backends (summit POIs + parks data) via the Gateway
  links:
    - url: http://klaus-mandola-poi-gateway-app-klaus-mandola.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh23-demo/klaus-mandola-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/meiersheinz"
  system: workshop-system-klaus-mandola
  definition:
    $text: https://github.com/rhdh23-demo/klaus-mandola-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
